language: erlang
install: true
before_script:
  - make setup-rebar3
  - make setup-hexpm
env: PATH=".:$PATH"
script:
  - make build-all
  - make check-all
otp_release:
  - 19.1
  - 18.3
  - 17.5
  - R16B03-1
  - R15B03
